export const JOB_CATEGORY_NAMES = [
  'Accounting & Finance',
  'Administration & Office Support',
  'Agriculture & Farming',
  'Architecture & Interior Design',
  'Banking & Financial Services',
  'Beauty & Wellness',
  'Business Development',
  'Call Center & Customer Service',
  'Construction & Skilled Trades',
  'Creative & Design',
  'Customer Service',
  'Data Science & Analytics',
  'Education & Training',
  'Engineering',
  'Healthcare & Medical',
  'Hospitality & Tourism',
  'Human Resources',
  'Information Technology (IT)',
  'Insurance',
  'Legal',
  'Logistics & Supply Chain',
  'Manufacturing & Production',
  'Marketing & Advertising',
  'Media & Communications',
  'NGO & Non-Profit',
  'Operations Management',
  'Procurement & Purchasing',
  'Project Management',
  'Property & Real Estate',
  'Quality Assurance',
  'Research & Development',
  'Retail & Wholesale',
  'Sales',
  'Science & Laboratory',
  'Security Services',
  'Social Services',
  'Software Development',
  'Telecommunications',
  'Textile & Apparel',
  'Transportation & Delivery',
  'Travel & Tourism',
  'Warehouse & Distribution',
  'Writing & Editing',
  'Government & Public Sector',
  'Other',
] as const;
